 <?php 
/**
* @file
* contact functionality for a contact info
*/
function contact_block_block_info() {
  $blocks = array();
  $blocks['my_block'] = array(
    'info' => t('Social Contact Info'),
  );
  
  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function contact_block_block_configure($delta='') {
  $form = array();
  
  switch($delta) {
    case 'my_block' :
      // Text field form element
      $form['text_facebook'] = array(
        '#type' => 'textfield',
        '#title' => t('Facebook'),
        '#default_value' => variable_get('text_facebook', ''),
      );
      $form['text_twitter'] = array(
        '#type' => 'textfield',
        '#title' => t('Twitter'),
        '#default_value' => variable_get('text_twitter', ''),
      );
      $form['text_google'] = array(
        '#type' => 'textfield',
        '#title' => t('Google+'),
        '#default_value' => variable_get('text_google', ''),
      );
      $form['text_rss'] = array(
        '#type' => 'textfield',
        '#title' => t('RSS'),
        '#default_value' => variable_get('text_rss', ''),
      );
 
      
      break;
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function contact_block_block_save($delta = '', $edit = array()) {
  switch($delta) {
    case 'my_block' :
      // Saving the WYSIWYG text      
      variable_set('text_facebook', $edit['text_facebook']);
      variable_set('text_twitter', $edit['text_twitter']);
      variable_set('text_google', $edit['text_google']);
      variable_set('text_rss', $edit['text_rss']);
    
      break;
  }
}


/**
 * Implements hook_block_view().
 */
function contact_block_block_view($delta='') {
  $block = array();
  
  switch($delta) {
    case 'my_block' :
      $block['content'] = my_block_view();
      break;
  }
  
  return $block;
}

/**
 * Custom function to assemble renderable array for block content.
 * Returns a renderable array with the block content.
 * @return
 *   returns a renderable array of block content.
 */
function my_block_view() {
  $block = array();


  // Capture WYSIWYG text from the variable
  $text_facebook = variable_get('text_facebook', '');
  $text_twitter = variable_get('text_twitter', '');
  $text_google = variable_get('text_google', '');
  $text_rss = variable_get('text_rss', '');

  // Block output in HTML with div wrapper
  $block = array(
    'message' => array(
      '#type' => 'markup',
      '#markup' =>  '<ul><li>' . t('Follow Us') . '</li><li><a class="facebook" href="' . $text_facebook . '">Facebook GPS mapping</a></li>',
      '#suffix' => '',
    ),
    'message2' => array(
      '#type' => 'markup',
      '#markup' =>  '<li><a class="twitter" href="' . $text_twitter . '">Twitter GPS mapping</a></li>',
      '#suffix' => '',
    ),
    'message3' => array(
      '#type' => 'markup',
      '#markup' =>  '<li><a class="google" href="' . $text_google . '"> Google GPS mapping</a></li>',
      '#suffix' => '',
    ),
    'message4' => array(
      '#type' => 'markup',
      '#markup' => '<li><a class="rss" href="' . $text_rss . '">RSS GPS mapping</a></li></ul>',
      '#suffix' => '',
    )    
  );

  return $block;
}
